services:
  rssdepot:
    container_name: rssdepot
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - PRODUCTION_HOSTS=${PRODUCTION_HOSTS}
    volumes:
      - ./app:/usr/src/app/
    ports:
      - "8111:8000"
  celeryworker:
    container_name: celeryworker
    build: ./app
    command: celery -A rssdepot worker -l INFO
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - PRODUCTION_HOSTS=${PRODUCTION_HOSTS}
    volumes:
      - ./app:/usr/src/app/
  celerybeat:
    container_name: celerybeat
    build: ./app
    command: celery -A rssdepot beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - PRODUCTION_HOSTS=${PRODUCTION_HOSTS}
    volumes:
      - ./app:/usr/src/app/
