services:
  valkey:
    container_name: valkey
    image: docker.io/valkey/valkey
    ports:
    - 6379:6379
  rssdepot:
    container_name: rssdepot
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - valkey
  celeryworker:
    container_name: celeryworker
    build: ./app
    command: celery -A rssdepot worker -l INFO
    environment:
      - CELERY_BROKER_URL=redis://valkey:6379
    volumes:
      - ./app:/usr/src/app/
    depends_on:
      - valkey
  celerybeat:
    container_name: celerybeat
    build: ./app
    command: celery -A rssdepot beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - CELERY_BROKER_URL=redis://valkey:6379
    volumes:
      - ./app:/usr/src/app/
    depends_on:
      - valkey