# Generated by Django 5.1.2 on 2024-11-11 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_created=True, verbose_name="date created"
                    ),
                ),
                ("hostname", models.URLField()),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=200)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                ("modified_at", models.DateTimeField(verbose_name="date modified")),
            ],
        ),
        migrations.CreateModel(
            name="FeedEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_created=True, verbose_name="date created"
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("authors", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("url", models.URLField()),
                ("in_feed", models.BooleanField(default=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                ("modified_at", models.DateTimeField(verbose_name="date modified")),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="feeds.feed",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entries",
            },
        ),
    ]
