# Generated by Django 5.1.2 on 2024-11-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0002_feedentry_backfilled"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="backfilled",
            field=models.BooleanField(default=False),
        ),
    ]
