# Generated by Django 5.1.2 on 2024-11-11 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0003_feed_backfilled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedentry",
            name="modified_at",
        ),
        migrations.AddField(
            model_name="feedentry",
            name="published_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 11, 7, 21, 11, 498604, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date published",
            ),
            preserve_default=False,
        ),
    ]
