# Generated by Django 5.1.3 on 2024-11-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_remove_feedentry_modified_at_feedentry_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='slug',
            field=models.CharField(default='blah', max_length=100),
            preserve_default=False,
        ),
    ]
